#!/bin/sh

export MY_NVIM="my-nvim"
export XDG_CONFIG_HOME="$HOME/.config/$MY_NVIM"
export NVIM_CONFIG_DIR="$XDG_CONFIG_HOME/nvim"
export NVIM_RUNTIME_DIR="$HOME/.local/share/$MY_NVIM"

ln -fns "$NVIM_RUNTIME_DIR" "$HOME/.local/share/nvim"
exec nvim -u "$NVIM_CONFIG_DIR/init.lua" "$@"

unset NVIM_RUNTIME_DIR
unset NVIM_CONFIG_DIR
unset XDG_CONFIG_HOME
unset MY_NVIM
